import { BossCardBody, type Boss } from "./BossCard";

/* ------------------------------------------------------------------ *
 * FILLED EXAMPLE — "Mo 'Curly' Pastrami".
 * Guardian of Infinite Flow / Keeper of the Eternal Groove.
 * Accent: ocean teal #14b8a6
 * ------------------------------------------------------------------ */
const MO: Boss = {
  name: "MO 'CURLY' PASTRAMI",
  titles: ["Guardian of Infinite Flow", "Keeper of the Eternal Groove"],
  planet: "Tidalia Prime",
  heroImage: "/__mockup/images/mo-full.png",
  originStory: [
    "Born on the ocean world of Tidalia Prime, Mo 'Curly' Pastrami grew up riding sonic waves generated by the planet's musical tides.",
    "While most Guardians trained for speed or technical perfection, Mo discovered something far more powerful — Flow.",
    "The great tidal reefs of Tidalia resonate with harmonic frequencies that can only be heard by those who truly listen.",
    "Through years of surfing both oceans and melodies, Mo learned to merge rhythm, expression and movement into a single force.",
  ],
  quote: "The wave already knows where it's going. Just ride it.",
  specialty: {
    title: "Specialty",
    body: "Melodic Improvisation, Legato, Groove, Feel, Phrasing & Musical Storytelling.",
    icon: "spark",
  },
  specialAbility: {
    title: "Sonic Tide",
    body: "Summons a massive wave of harmonic energy that carries every note perfectly into the pocket. Boosts groove by 200%, increases melodic awareness, and makes bad timing impossible.",
    icon: "infinity",
  },
  guardianPower: {
    title: "Infinite Flow",
    body: "The longer Mo plays, the stronger he becomes. Immune to overthinking, unlocks spontaneous creativity, and converts mistakes into musical ideas.",
    icon: "planet",
  },
  funFacts: [
    "Surfs black holes for fun.",
    "Once improvised a solo for three days straight.",
    "Has never owned a metronome.",
    "Can detect a wrong note from another solar system.",
    "His hair has its own weather system.",
  ],
  attributes: [
    { label: "Speed", value: 9 },
    { label: "Technique", value: 9 },
    { label: "Creativity", value: 10 },
    { label: "Tone", value: 10 },
    { label: "Stamina", value: 9 },
    { label: "Style", value: 10 },
  ],
  unlock: { text: "Complete all Groove Challenges and earn 70,000 XP" },
  difficulty: 4,
  difficultyTagline: "Ride the wave. Shred everything.",
  accentColor: "#14b8a6",
  gallery: [
    { label: "Signature Guitar", src: "/__mockup/images/mo-guitar.png" },
    { label: "Guitar Close-Up", src: "/__mockup/images/mo-guitar-closeup.png" },
    { label: "Avatar Front", src: "/__mockup/images/mo-full.png" },
  ],
};

export function BossCardMo() {
  return <BossCardBody boss={MO} />;
}
